version: '3.8'

services:
  jira:
    image: atlassian/jira-software:latest
    ports:
      - "8080:8080"
    environment:
      - JVM_MINIMUM_MEMORY=1024m
      - JVM_MAXIMUM_MEMORY=4096m
    depends_on:
      - db
    networks:
      - jira_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=jiradb
      - POSTGRES_USER=jirauser
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - jira_network

networks:
  jira_network:

volumes:
  db_data:
